[package]
name = "lemonmath"
description = "A math library"
authors = ["LonnonjamesD"]
version = "0.1.0"
edition = "2021"
license = "GNU GPLv3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]